version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: sdks/python
      extra_requirements:
        - gcp
        - aws

sphinx:
  configuration: docs/source/conf.py
